trigger:
   tags:
     include:
       - '*'
     exclude:
       - latest
   branches:
     exclude:
       - '*'
pr: none
<<<<<<< HEAD
schedules:
- cron: "0 3 * * *" # 10 pm EST->UTC
  displayName: Daily build
  branches:
    include:
    - develop
  always: false
=======
>>>>>>> originSimpleITK/master

# Scheduled builds on master to build the "latest" are configure through the AZP GUI.

jobs:
  - job: Configure
    displayName: Configure Variables
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - checkout: none
      - bash: |
          echo "##vso[task.setvariable variable=BuildHash;isOutput=true]${CONFIGURE_BUILDHASH:-release}"
        name: configure
  - template: templates/package-linux-job.yml
    parameters:
        DOCKERFILE: Dockerfile-2010-x86_64
  - template: templates/package-linux-job.yml
    parameters:
        DOCKERFILE: Dockerfile-x86_64
  - template: templates/package-mac-job.yml
  - template: templates/package-win-job.yml
    parameters:
      PYTHON_ARCH: x64
      CMAKE_PLATFORM: x64
      VCVAR_OPTIONS: amd64
<<<<<<< HEAD
=======
  - job: Doxygen
    dependsOn: Configure
    condition: ne( variables['configure.doxygen'], 'true' )
    timeoutInMinutes: 60
    variables:
      SIMPLEITK_GIT_TAG: $[ dependencies.Configure.outputs['configure.BuildHash'] ]
    steps:
      - template: templates/git-download-steps.yml
      - bash: |
          cd ${BUILD_SOURCESDIRECTORY}/Utilities/Doxygen/docker
          docker build -f Dockerfile -t simpleitk-doxygen .
        displayName: Build Docker Image
      - bash: |
          docker run \
                 --mount type=bind,source=${BUILD_SOURCESDIRECTORY},destination=/work/SimpleITK,readonly \
                 --env SIMPLEITK_GIT_TAG \
                 --name sitk-dox simpleitk-doxygen
          mkdir -p $(Build.ArtifactStagingDirectory)/Doxygen
          docker cp sitk-dox:/SimpleITKDoxygen.tar.gz $(Build.ArtifactStagingDirectory)/Doxygen/SimpleITKDoxygen-${SIMPLEITK_GIT_TAG}.tar.gz
        displayName: Docker doxygen generation
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/Doxygen
          artifactName: Doxygen
>>>>>>> originSimpleITK/master
