jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: CMake@1
    displayName: 'CMake Generate'
    inputs:
      cmakeArgs: '../SuperBuild'
  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      cmakeArgs: --build .
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: CMake@1
    displayName: 'CMake Generate'
    inputs:
      cmakeArgs: '../SuperBuild'
  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      cmakeArgs: --build .
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 4
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - task: CMake@1
    displayName: 'CMake Generate'
    inputs:
      cmakeArgs: -G "Visual Studio 15 2017 Win64" '../SuperBuild'
  - task: CMake@1
    displayName: 'CMake Build'
    inputs:
      cmakeArgs: --build .
