name: Elastix

on: [push, pull_request]
  
jobs:
  build:
    
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.5.3'
       
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ninja
        
    - name: Run SuperBuild
      run: |
        cd ..
        mkdir build
        cd build
        cmake ../SimpleElastix/SuperBuild
        make -j4
        
    - name: Check Results
      run: | 
        cd ..
        cd build/SimpleITK-build/Wrapping
        ls
        
    - name: Check Results Python
      run: | 
        cd ..
        cd build/SimpleITK-build/Wrapping/Python
        ls    
        
    - name: Check Results R
      run: | 
        cd ..
        cd build/SimpleITK-build/Wrapping/R
        ls
